### ISSUE TITLE
Create a new post

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-dramatic-chipmunks#11]
As a gifophile, I would like to author a post

**Given** that a person wants to share a funny gif
**When** the person clicks on the button to create a gif
**Then** the person should see a form to enter in a title, the image's URL, and a description

**Given** that a person has entered in all of the fields of the post form
**When** the person clicks on the save button
**Then** the person should see their new post in the post list

**Comment by pracinejr** [comment]
- create HTML for giffygram.js (general page layout)

- create the PostEntry.js module and format the form
> fetch function to get the posts data from database - getter function

- create the 'new post' form
> 2 text fields, 1 URL field

- fetch - POST function

- validate function to make sure all fields are filled out before submission 
> create red text alert under the button field

**Comment by joelbeckum** [comment]
Test comment - Joel is working on issue so and so
