### ISSUE TITLE
Log in with existing credentials

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-dramatic-chipmunks#12]
As a gifophile, I want to log in with my credentials

**Given** that a person wants to use Giffygram
**And** has entered in a valid email and password
**When** the person clicks on the login button
**Then** the person should see the list of posts

**Comment by pracinejr** [comment]
-write a fetch call to get the information from the data base
-write a getter to get the information from application state
-statechange listener on main.js

**Comment by joelbeckum** [comment]
- created fetchExternalData function to populate all needed data fields in application state
- created and exported getters for all relevant application state data
- refactored main.js to correctly render page
- implemented event listener to register stateChanged broadcasted from Login.js module
