### ISSUE TITLE
Read private messages

### ISSUE THREAD

**Issue by JoeShep** [NSS-Day-Cohort-49/giffygram-dramatic-chipmunks#3]
As an authenticated user, I would like to be able to read all private messages sent to me by other users

**Given** that a person has provided proper authentication details
**When** the person is viewing the post feed
**And** there are 1+ unread messages sent from other users
**Then** there should be a notification in the navigation bar displaying the number of messages

**Given** that a person has provided proper authentication details
**And** there are 1+ unread messages sent from other users
**When** the person clicks the notification affordance
**Then** the post feed should be replaced with a list of messages

**Given** that a person has provided proper authentication details
**And** the person is viewing the message list
**When** the person clicks the application icon i the navigation bar
**Then** the list of messages should be replaced with a list of posts

**Comment by pracinejr** [comment]
- filter out all messages that match the gg_user
- filter through filtered.messages and count how many have a 'read' value of false -> run .length on the array that is set to the variable holding UNREAD messages
- new messages icon number is set to the .length total
- click event listener on messages icon
>  when clicked the #maincontainer HTML should be repopulated with the Messages list
- click event listener on application icon
>  when clicked the #maincontainer HTML should be repopulated with the posts list
